server:
  error:
    include-stacktrace: never

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/PharmacySystem1?createDatabaseIfNotExist=true
    username: root
    password: